# Generated by Django 4.2.13 on 2024-05-27 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_family_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spouseinfo',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouses', to='main.person'),
        ),
    ]
