# Generated by Django 4.2.13 on 2024-06-03 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='children', to='main.person'),
        ),
        migrations.AlterField(
            model_name='family',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_of', to='main.person'),
        ),
        migrations.AlterField(
            model_name='family',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_of', to='main.person'),
        ),
        migrations.AlterField(
            model_name='spouseinfo',
            name='spouse_fathername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spouseinfo',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spouseinfo',
            name='spouse_village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
