# Generated by Django 4.2.13 on 2024-06-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_family_children_alter_family_father_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(related_name='children', to='main.person'),
        ),
    ]
