# Generated by Django 4.2.13 on 2024-06-26 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_family_children'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='spouseinfo',
            options={'verbose_name_plural': 'Spouse Information'},
        ),
        migrations.AlterField(
            model_name='spouseinfo',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_info', to='main.person'),
        ),
    ]
