# Generated by Django 4.2.13 on 2024-06-27 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spouseinfo',
            options={},
        ),
    ]
